// <auto-generated />
using Kursova.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kursova.Migrations
{
    [DbContext(typeof(AutoDbContext))]
    partial class AutoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kursova.Data.Entitys.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.ToTable("Autos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 3,
                            Mark = "Audi",
                            Model = "80",
                            Price = 2500.0,
                            Year = 1978
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 1,
                            Mark = "Mazda",
                            Model = "RX7",
                            Price = 2300.0,
                            Year = 1978
                        },
                        new
                        {
                            Id = 3,
                            ColorId = 2,
                            Mark = "Toyota",
                            Model = "Land Cruiser",
                            Price = 7000.0,
                            Year = 2017
                        },
                        new
                        {
                            Id = 4,
                            ColorId = 5,
                            Mark = "ZAZ-1103",
                            Model = "Slavuta",
                            Price = 1500.0,
                            Year = 1988
                        },
                        new
                        {
                            Id = 5,
                            ColorId = 4,
                            Mark = "BMW",
                            Model = "X5",
                            Price = 5000.0,
                            Year = 1999
                        });
                });

            modelBuilder.Entity("Kursova.Data.Entitys.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorName = "Blue"
                        },
                        new
                        {
                            Id = 2,
                            ColorName = "Yellow"
                        },
                        new
                        {
                            Id = 3,
                            ColorName = "Gray"
                        },
                        new
                        {
                            Id = 4,
                            ColorName = "White"
                        },
                        new
                        {
                            Id = 5,
                            ColorName = "Black"
                        },
                        new
                        {
                            Id = 6,
                            ColorName = "Green"
                        },
                        new
                        {
                            Id = 7,
                            ColorName = "Red"
                        });
                });

            modelBuilder.Entity("Kursova.Data.Entitys.Auto", b =>
                {
                    b.HasOne("Kursova.Data.Entitys.Color", "Color")
                        .WithMany("Autos")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");
                });

            modelBuilder.Entity("Kursova.Data.Entitys.Color", b =>
                {
                    b.Navigation("Autos");
                });
#pragma warning restore 612, 618
        }
    }
}
